name: Release Existence Action
author: Roche/Genentech - Insights Engineering
description: Check if a release for given tag exists

inputs:
  release-tag:
    description: The name of tag for which it should be checked whether the release exists
    required: false
    default: ""
outputs:
  release-created:
    description: "Whether the release for given tag has been created"
    value: ${{ steps.get-latest-release.outputs.release-created }}

# TODO
branding:
  icon: 'image'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Get branch names 🌿
      id: branch-names
      uses: tj-actions/branch-names@v6

    - name: Get latest release 🚀
      id: get-latest-release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Current tag = ${{ steps.branch-names.outputs.tag }}"
        RELEASE_TAG="${{ steps.branch-names.outputs.tag }}"
        if [[ "${{ inputs.release-tag }}" != "" ]]; then
          echo "Setting release tag to check to ${{ inputs.release-tag }}"
          RELEASE_TAG="${{ inputs.release-tag }}"
        fi
        set +e
        if [[ "$(gh release view $RELEASE_TAG 2>&1)" == "release not found" ]]; then
          echo "Release not found."
          echo "release-created=false" >> $GITHUB_OUTPUT
        else
          echo "Release found."
          echo "release-created=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
