---
name: SuperLinter 🦸🏻‍♀️
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint Code Base 🧶
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: Lint Code Base 🧶
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
