name: Test this action 🧪
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test this action 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 🛎️
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Check if release exists
        uses: ./
        with:
          release-tag: "v1.0.0"
